// Model Definition

// Defining an array of objects with song info.
var saraliVarisais = [
		{title: 'Varisai 1', lines: ['s r g m | p d | n S ||', 'S n d p | m g | r s ||']},
		{title: 'Varisai 2', lines: ['s r - s r - | s r | g m ||', 's r g m | p d | n S ||',	
		'S n - S n - | S n | d p ||', 'S n d p | m g | r s ||']},
		{title: 'Varisai 3', lines: ['s   r   g -  s   |   r   g - |   s   r   ||', 's   r   g   m   |   p   d   |   n   S   ||',
		'S   n   d - s   |   n   d - |   s   n   ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 4', lines: ['s   r   g   m - |   s   r   |   g   m - ||', 's   r   g   m   |   p   d   |   n   s   ||',
		'S   n   d   p - |   S   n   |   d   p - ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 5', lines: ['s   r   g   m   |   p   , - |   s   r   ||', 's   r   g   m   |   p   d   |   n   S   ||',
		'S   n   d   p   |   m   , - |   S   n   ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 6', lines: ['s   r   g   m   |   p   d - |   s   r   ||', 's   r   g   m   |   p   d   |   n   S   ||',
		'S   n   d   p   |   m   g - |   S   n   ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 7', lines: ['s   r   g   m   |   p   d   |   n   ,   ||', 's   r   g   m   |   p   d   |   n   S   ||',
		'S   n   d   p   |   m   g   |   r   ,   ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 8', lines: ['s   r   g   m   |   p   m   |   g   r   ||', 's   r   g   m   |   p   d   |   n   S   ||',
		'S   n   d   p   |   m   p   |   d   n   ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 9', lines: ['s   r   g   m   |   p   m   |   d   p   ||', 's   r   g   m   |   p   d   |   n   S   ||',
		'S   n   d   p   |   m   p   |   g   m   ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 10', lines: ['s   r   g   m   |   p   ,   |   g   m   ||', 'p   ,   ,   ,   |   p   ,   |   ,   ,   ||',
		'g   m   p   d   |   n   d   |   p   m   ||', 'g   m   p - g   |   m   g   |   r   s   ||']},
		{title: 'Varisai 11', lines: ['S   ,   n   d   |   n   ,   |   d   p   ||', 'd   ,   p   m   |   p   ,   |   p   ,   ||',
		'g   m   p   d   |   n   d   |   p   m   ||', 'g   m   p - g   |   m   g   |   r   s   ||']},
		{title: 'Varisai 12', lines: ['S   S   n   d   |   n   n   |   d   p   ||', 'd   d   p   m   |   p   ,   |   p   ,   ||',
		'g   m   p   d   |   n   d   |   p   m   ||', 'g   m   p - g   |   m   g   |   r   s   ||']},
		{title: 'Varisai 13', lines: ['s   r   g   r   |   g   , - |   g   m   ||', 'p   m   p   , - |   d   p   |   d   ,   ||',
		'm   p   d   p   |   d   n   |   d   p   ||', 'm   p   d   p   |   m   g   |   r   s   ||']},
		{title: 'Varisai 14', lines: ['s   r   g   m   |   p   ,   |   p   ,   ||', 'd   d   p   ,   |   m   m   |   p   ,   ||',
		'd   n   S   ,   |   S   n   |   d   p   ||', 'S   n   d   p   |   m   g   |   r   s   ||']},
	];
